"""
Basic sanity tests for the lexicon fixture files.

Assumes the fixtures have already been generated by scripts/fetch_lexicons.py.
Run with:  pytest tests/test_lexicons.py
"""

import json
from pathlib import Path

import pytest

FIXTURES_DIR = Path("data/fixtures")

LEXICON_FILES = {
    "bdb":    FIXTURES_DIR / "lex_bdb.json",
    "thayer": FIXTURES_DIR / "lex_thayer.json",
    "lsj":    FIXTURES_DIR / "lex_lsj.json",
}

MIN_ENTRIES = 100


@pytest.fixture(scope="module", params=list(LEXICON_FILES.keys()))
def lexicon(request):
    """Load each lexicon fixture once per module."""
    name = request.param
    path = LEXICON_FILES[name]
    if not path.exists():
        pytest.skip(f"{path} not found — run scripts/fetch_lexicons.py first")
    with path.open(encoding="utf-8") as f:
        data = json.load(f)
    return name, data


def test_min_entry_count(lexicon):
    name, data = lexicon
    assert len(data) >= MIN_ENTRIES, (
        f"{name}: expected >= {MIN_ENTRIES} entries, got {len(data)}"
    )


def test_all_values_are_dicts(lexicon):
    name, data = lexicon
    bad = [k for k, v in data.items() if not isinstance(v, dict)]
    assert not bad, f"{name}: non-dict values for keys: {bad[:5]}"


def test_all_entries_have_lemma(lexicon):
    name, data = lexicon
    missing = [k for k, v in data.items() if not v.get("lemma")]
    pct = 100 * len(missing) / max(len(data), 1)
    assert pct < 5.0, (
        f"{name}: {len(missing)} entries ({pct:.1f}%) missing 'lemma'"
    )


def test_all_entries_have_gloss(lexicon):
    name, data = lexicon
    missing = [k for k, v in data.items() if not v.get("gloss")]
    pct = 100 * len(missing) / max(len(data), 1)
    assert pct < 5.0, (
        f"{name}: {len(missing)} entries ({pct:.1f}%) missing 'gloss'"
    )


def test_all_entries_have_definition(lexicon):
    name, data = lexicon
    missing = [k for k, v in data.items() if not v.get("definition")]
    pct = 100 * len(missing) / max(len(data), 1)
    # definition may be the same as gloss for terse entries; allow more slack
    assert pct < 10.0, (
        f"{name}: {len(missing)} entries ({pct:.1f}%) missing 'definition'"
    )


def test_keys_look_like_strongs_numbers(lexicon):
    """Most keys should start with H (Hebrew) or G (Greek) followed by digits."""
    name, data = lexicon
    import re
    strongs_re = re.compile(r"^[HG]\d+")
    good = sum(1 for k in data if strongs_re.match(k))
    pct = 100 * good / max(len(data), 1)
    assert pct >= 80.0, (
        f"{name}: only {good}/{len(data)} ({pct:.1f}%) keys match Strong's format"
    )


def test_no_empty_string_values(lexicon):
    """All three required fields should be non-empty strings."""
    name, data = lexicon
    bad = []
    for key, entry in data.items():
        for field in ("lemma", "gloss", "definition"):
            val = entry.get(field, "")
            if not isinstance(val, str):
                bad.append((key, field, type(val).__name__))
    assert not bad, f"{name}: wrong types: {bad[:5]}"
